USE sakila;

-- 1. List the number of films per category.
SELECT ca.name, f.title
FROM sakila.film AS f
JOIN sakila.film_category as c
ON f.film_id = c.film_id
JOIN sakila.category AS ca
ON c.category_id = ca.category_id
ORDER BY ca.name;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city, co.country
FROM sakila.address AS a
JOIN sakila.store AS s
ON a.address_id = s.address_id
JOIN sakila.city AS c
ON a.city_id = c.city_id
JOIN sakila.country AS co
ON c.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT i.store_id, SUM(p.amount) AS revenue
FROM sakila.rental AS r
JOIN sakila.payment AS p
ON r.rental_id = p.rental_id
JOIN sakila.inventory AS i
ON r.inventory_id = i.inventory_id
GROUP BY i.store_id;

-- 4. Determine the average running time of films for each category.
SELECT c.name, AVG(f.length) AS avg_length
FROM sakila.film AS f
JOIN sakila.film_category AS ca
ON f.film_id = ca.film_id
JOIN sakila.category AS c
ON ca.category_id = c.category_id
GROUP BY c.name;

